# Generated by Django 5.2.6 on 2025-09-18 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_anime'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='subscription_month',
            field=models.CharField(default='January', max_length=20),
        ),
        migrations.AddField(
            model_name='anime',
            name='subscription_year',
            field=models.IntegerField(default=2025),
        ),
    ]
