# Generated by Django 5.2.6 on 2025-09-23 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_anime_subscription_month_anime_subscription_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='hours',
            field=models.DecimalField(decimal_places=1, default=1.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='anime',
            name='language',
            field=models.CharField(default='Japanese', max_length=50),
        ),
        migrations.AddField(
            model_name='anime',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='episode_price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='anime',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='anime',
            name='season_list',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='anime',
            name='subscription_month',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='anime',
            name='subscription_year',
            field=models.PositiveIntegerField(),
        ),
    ]
