# Generated by Django 5.2.6 on 2025-09-23 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_anime_hours_anime_language_anime_year_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='anime_images/')),
                ('season_list', models.CharField(max_length=200)),
                ('episode_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('hours', models.DecimalField(decimal_places=1, default=1.0, max_digits=4)),
                ('language', models.CharField(default='Japanese', max_length=50)),
                ('subscription_month', models.CharField(max_length=20)),
                ('subscription_year', models.PositiveIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='anime',
            name='hours',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='language',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='subscription_month',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='subscription_year',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='year',
        ),
        migrations.AlterField(
            model_name='anime',
            name='episode_price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='anime',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='anime',
            name='season_list',
            field=models.TextField(),
        ),
    ]
