# Generated by Django 5.2.6 on 2025-09-23 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_animation_remove_anime_hours_remove_anime_language_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Animation',
        ),
        migrations.AddField(
            model_name='anime',
            name='hours',
            field=models.DecimalField(decimal_places=1, default=1.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='anime',
            name='language',
            field=models.CharField(default='Japanese', max_length=50),
        ),
        migrations.AddField(
            model_name='anime',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
