# Generated by Django 5.2.6 on 2025-09-23 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_delete_animation_anime_hours_anime_language_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='year',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='hours',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='language',
        ),
        migrations.CreateModel(
            name='AnimeDetail',
            fields=[
                ('anime_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myapp.anime')),
                ('year', models.IntegerField(blank=True, null=True)),
                ('hours', models.DecimalField(decimal_places=1, default=1.0, max_digits=4)),
                ('language', models.CharField(default='Japanese', max_length=50)),
            ],
            bases=('myapp.anime',),
        ),
    ]
