# Generated by Django 5.2.6 on 2025-10-15 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_remove_anime_year_remove_anime_hours_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnimeDetail',
        ),
    ]
