# Generated by Django 5.2.6 on 2025-10-15 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_delete_animedetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimeDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(blank=True, null=True)),
                ('hours', models.DecimalField(decimal_places=1, default=1.0, max_digits=4)),
                ('language', models.CharField(default='Japanese', max_length=50)),
                ('anime', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='details', to='myapp.anime')),
            ],
        ),
    ]
