# Generated by Django 5.2.6 on 2025-10-15 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_animedetail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnimeDetail',
        ),
    ]
