# Generated by Django 5.2.6 on 2025-10-16 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_animedetail_episode'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(choices=[('Mobile', 'Mobile'), ('Super', 'Super'), ('Premium', 'Premium')], max_length=20)),
                ('duration_months', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('price_per_month', models.PositiveIntegerField()),
                ('resolution', models.CharField(max_length=50)),
                ('device_limit', models.PositiveIntegerField()),
                ('devices_supported', models.CharField(max_length=100)),
                ('ads', models.BooleanField(default=True)),
                ('audio_quality', models.CharField(max_length=50)),
                ('video_quality', models.CharField(max_length=50)),
                ('special_note', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
