# Generated by Django 5.2.6 on 2025-11-04 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_subscriptionplan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='resolution',
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='ads',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='plan_type',
            field=models.CharField(choices=[('Basic', 'Basic'), ('Standard', 'Standard'), ('Premium', 'Premium')], max_length=20),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='price_per_month',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='special_note',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
