# Generated by Django 5.2.6 on 2025-11-04 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_remove_subscriptionplan_resolution_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubscriptionPlan',
        ),
    ]
