# Generated by Django 5.2.6 on 2025-11-04 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_delete_subscriptionplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(choices=[('Mobile', 'Mobile'), ('Super', 'Super'), ('Premium', 'Premium')], max_length=50)),
                ('devices', models.IntegerField(default=1)),
                ('description', models.TextField(blank=True, null=True)),
                ('has_ads', models.BooleanField(default=True)),
                ('resolution', models.CharField(default='HD 720p', max_length=50)),
                ('sound_quality', models.CharField(default='Stereo', max_length=50)),
                ('duration_months', models.IntegerField(default=3)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('price_per_month', models.DecimalField(decimal_places=2, max_digits=6)),
                ('features', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
