# Generated by Django 5.2.6 on 2025-11-24 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='episode_price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='anime',
            name='image',
            field=models.ImageField(upload_to='anime_main/'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='season_list',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='episode',
            name='duration',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='AnimeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='anime_gallery/')),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='myapp.anime')),
            ],
        ),
    ]
