# Generated by Django 5.2.6 on 2025-11-24 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_alter_anime_episode_price_alter_anime_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='episode_price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='anime',
            name='image',
            field=models.ImageField(upload_to='anime_images/'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='season_list',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='episode',
            name='duration',
            field=models.CharField(max_length=20),
        ),
        migrations.DeleteModel(
            name='AnimeImage',
        ),
    ]
